"""empty message

Revision ID: 29ea461ab6df
Revises: c07f9cc8bc56
Create Date: 2018-03-06 11:24:27.807978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ea461ab6df'
down_revision = 'c07f9cc8bc56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('titles', sa.String(length=100), nullable=False))
    op.drop_column('books', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('books', 'titles')
    # ### end Alembic commands ###
