"""empty message

Revision ID: b5077daaf626
Revises: 
Create Date: 2018-03-06 11:23:16.771925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5077daaf626'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('titles', sa.String(length=80), nullable=False))
    op.drop_column('books', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('books', 'titles')
    # ### end Alembic commands ###
