"""empty message

Revision ID: c07f9cc8bc56
Revises: b5077daaf626
Create Date: 2018-03-06 11:23:56.884127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07f9cc8bc56'
down_revision = 'b5077daaf626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.String(length=80), nullable=False))
    op.drop_column('books', 'titles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('titles', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('books', 'title')
    # ### end Alembic commands ###
